import MainLayout from "@/components/Layouts/MainLayout";
import "./globals.css";
// import Header from "@/components/Layouts/Header";
// import Footer from "@/components/Layouts/Footer";
import Providers from "@/components/providers/Providers";
import { AuthProvider } from "@/context/AuthContext";
import { cookies } from "next/headers";

export const metadata = {
  title: "Store",
  description: "Generated by create next app",
};

const cookiesStore = cookies();
const token = cookiesStore.get('token');

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="fa">
      <body>
        <Providers>
          <AuthProvider>
              <div>{children}</div>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
